FROM yylt/falco-build:0.29.1-202108120821

ARG FALCO_VERSION=0.29.1

COPY . /
RUN  yum install autoconf \
        libtool \
        git \
        bison \
        flex \
        ruby \
        wget  -y && \
    pip3 install pipenv && \    
    cd jq && cd docs && pipenv sync && cd .. && \
    git submodule init && \
    git submodule update && \
    autoreconf -i && \
    ./configure --disable-valgrind --enable-all-static --prefix=/usr/local && \
    make -j8 && \
    make check && \
    make install

RUN cd /tmp && \
    curl -L https://github.com/falcosecurity/falco/archive/refs/tags/${FALCO_VERSION}.tar.gz | tar xz  && \
    cd falco-${FALCO_VERSION} && \
    mkdir -p "build" && \
    cd "build" && \
    cmake -DMINIMAL_BUILD=On -DBUILD_BPF=Off -DBUILD_DRIVER=Off -DCMAKE_BUILD_TYPE=Release .. && \
    sed -i 's/v1.2.1/v1.4.1/g' falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/cmake/modules/b64.cmake && \
    sed -i 's/d620e7caf3ed5f9c28d727fa799918ad3ef69c80975905646bb549a6019cdcbd/0fa93fb9c4fb72cac5a21533e6d611521e4326f42c19cc23f8ded814b0eca071/g' falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/cmake/modules/b64.cmake && \
    make && make install && \
    rm /tmp/*
